version: '3'
services:

  ######### INFRASTRUCTURE #########
  mosquitto:
    image: eclipse-mosquitto
    volumes: 
     - ./infrastructure/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf


  ##################################
  ###### WarehouseManagement #######

  warehouse-management:
    build: ./WarehouseManagement
    ports: 
      - "5000:5000"
  
  warehouse-management-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
     "-app-id", "WarehouseManagement",
     "-app-port", "5000"
    #  "-placement-host-address", "placement:50006"
     ]
    volumes:
        - "./dapr/components/:/components"
    depends_on:
      - WarehouseManagement
    network_mode: "service:warehouse-management"

  ##################################
  ###### Simulation #######

  simulation:
    build: ./StockDeliverySimulation
    depends_on: 
      - WarehouseManagement
    environment: 
      - MQTT_HOST=mosquitto

  # placement:
  #   image: "daprio/dapr"
  #   command: ["./placement", "-port", "50006"]
  #   ports:
  #     - "50006:50006"