version: '3'
services:

  ######### INFRASTRUCTURE #########
  mosquitto:
    image: eclipse-mosquitto
    volumes: 
     - ./infrastructure/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  redis:
    image: bitnami/redis:latest
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  ##################################
  ###### WarehouseManagement #######

  warehouse-management:
    build: ./WarehouseManagement
    ports: 
      - "5000:80"
      - "9090:9090"
  
  warehouse-management-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "-app-id", "WarehouseManagement",
      "-app-port", "80",
      "-components-path", "./components",
      "-log-as-json", "true",
      "config", ./config.yaml
      # "-placement-host-address", "placement:50006"
     ]
    volumes:
      - "./dapr/components/:/components"
      - "./WarehouseManagement/dapr-config.yaml:/config.yaml"
    depends_on:
      - warehouse-management
      # - placement
      - mosquitto
    network_mode: "service:warehouse-management"

  ##################################
  ###### Simulation #######

  simulation:
    build: ./StockDeliverySimulation
    depends_on: 
      - warehouse-management
      - mosquitto
    environment: 
      - MQTT_HOST=mosquitto

  ##################################
  ###### Dapr #######

  # placement:
  #   image: "daprio/dapr"
  #   command: ["./placement", "-port", "50006"]
  #   ports:
  #     - "50006:50006"