apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: entrysensor
  namespace: dapr-warehouse
spec:
  type: bindings.mqtt
  version: v1
  metadata:
  - name: url
    value: mqtt://mosquitto:1883
  - name: topic
    value: stockupdate/entrysensor
scopes:
  - WarehouseManagement
