apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: stockStateStore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: sOmE_sEcUrE_pAsS
scopes:
  - WarehouseManagement